apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: announcement
  namespace: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.188.240-172.16.188.254
